env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git  -b arrow-11.0
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/ManitnjG/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: arrow_${DEVICE}-userdebug
    OUTPUT: A*.zip
    CLO: 1:X01BD
    CLO_1: ENCRYPTED[e7ab02eedd4bb8522b9025b370b6ddc2ab0df932a38e19078fa21d2ac7df344ed2838a68295978cccb0a8246ef6f822a] 
    URI: https://doc-0k-10-docs.googleusercontent.com/docs/securesc/mbeibot9d2v7ocpv82t3u3cu7n1ii9ko/kmuvnc60q8fla0a10aj2oqpm1u2i8p6e/1689724575000/01826290593982067000/01826290593982067000/1jjJJx4bvmNDqp6wrDjuna7YbCjqZfJ5T?e=download&ax=AGtFMPWuHYo2Qoy9UgMsNCemVmzWfCown1FbsSrYTUEUP1Tcscr9iFVyMrKeGSFXJEk0JtdZEyVJlv5W3yM6hyoyFJ778v_j8YPumQMzR8B_RS7XkSezG62Ly8aivSUuFu5xFl7GWb1WqJs7Sgj5BV9Hf56sm1Q3SlBSjWl9B0EEn4ZCsqLw8V-DKMYP6KZqRrJ6WxFjpP6zBxUuFbqwA5q1csemQQpcaT92TmwAxMB00aD5t9X6b18kVuHh30UkCKicgBCzvgEZVzDwYtgzwkHHIpTHcTPQ-CGxoJPehdVpaix0SOaOZq53BbaZdEF83O9X1WaxvxCR5J5K1sIj67NZalmPJOyf8j81qBRNJ6oiK8b6vLPtf-B0mCxe9kRmTb9P-0S0MwuZ90zEKGvJvGjNZHxUVvSHf8XFXNeICrXNXMZ-9LaORv55bGHCM7rNX2Ny9PakeaIXhrE6r--GiYcmtHdJIL_rz40QTU7mzsXjyW7ffCQfkbH41gnEZj3lN6Y0DJ79JSM1MrGKvVPvFdwXFo0N31R64e27kzCUcYBVl4G2j3GU5gYYm7izAXGlKq5AWf672Rh7AkGEq5hM07ZjMIj1JqwajFc-Pjg5TrQVMLZ5dy7ywt9U2jO11-7rQ56xZWAXXsz3cJk2Ap0o166Ajxvs2inEgFVnjGQX720NZ0wFGBK3S7rYJlCcjaEh-Ge_AJm9b9tlroEN0zhy5wYVYkcrpdeIOT_fnY1ZW9R0wJt_SWwmsJcVfrEjuEvTXHV3j-zB01ACn9UGVee8XO6p9_ODzcOreVfyrJJT8sjNmbM0uVT0DwW3ds57QGcb0r6NrP1FwYU9XmzRYORuWnlCBLLTgV6nnzS8P5OaR9ONCrTMMuWswXvlN9iFdCj6Qe-pgA&uuid=912dc53c-c74d-4c69-abb6-c7af7b91493d&authuser=0&nonce=684n2e9lsg7q4&user=01826290593982067000&hash=8m03h7ehb4j2kotpr0jfr6ob14u28dmf
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
