env:
    MANIFEST: https://github.com/Octavi-Staging/manifest.git -b thirteen
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/ManitnjG/local_manifest.git -b oct
    TARGET: bacon
    LUNCH_COMBO: octavi_${DEVICE}-userdebug
    OUTPUT: O*.zip
    CLO: 1:X01BD
    CLO_1: ENCRYPTED[e7ab02eedd4bb8522b9025b370b6ddc2ab0df932a38e19078fa21d2ac7df344ed2838a68295978cccb0a8246ef6f822a] 
    URI: https://excellmedia.dl.sourceforge.net/project/fleur/ccache/Octavi/ccache.tar.gz
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
