#!/bin/bash
cd ~/work

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 10G
ccache -o compression=true
ccache -z
export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
export ALLOW_MISSING_DEPENDENCIES=true 
export TARGET_RELEASE=ap1a
rm -rf vendor/voltage
git clone https://github.com/ManitnjG/android_vendor_superior -b fourteen vendor/superior
. build/envsetup.sh
brunch X01BD
