#!/bin/bash

sync() {
    mkdir -p ~/work
    cd ~/work
    repo init --depth=1 -u $MANIFEST
    git clone $LOCAL_MANIFEST -b cip .repo/local_manifests
    repo sync -c -j8 --force-sync --optimized-fetch --no-tags --no-clone-bundle

    # After repo sync completes, clone additional repository
    if [ $? -eq 0 ]; then
        echo "Repo sync completed successfully."
        echo "Cloning additional repository..."

        if [ $? -eq 0 ]; then
            echo "Additional repository cloned successfully."
        else
            echo "Failed to clone additional repository."
            exit 1
        fi
    else
        echo "Repo sync failed. Exiting..."
        exit 1
    fi
}

echo "Syncing Rom and Device Sources..."
sync

