#!/bin/bash
sync() {
mkdir -p ~/work
cd ~/work
repo init --depth=1 -u $MANIFEST
git clone $LOCAL_MANIFEST  -b sup .repo/local_manifests
repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle -j8
rm -rf vendor/superior
git clone https://github.com/ManitnjG/android_vendor_superior.git -b fourteen vendor/superior
}

echo "Syncing Rom and Device Sources..."
sync
